name: Private Action Loader TS
description: Enables private Actions to be easily reused across repositories.
inputs:
  repo-token:
    description: 'Access token with read access to the repo containing action'
    required: true
  repo-name:
    description: 'The organization/user and repo where action is stored, with support for @ref'
    required: true
  custom-command:
    description: 'Command to be executed before running the action. Useful for building typescript actions'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'lock'
  color: 'green'
