name: Private Action Loader TS
description: Enables private Actions to be easily reused across repositories.
inputs:
  sonar-token:
    description: 'Required for .net solutions, for js/ts solutions use environment'
    required: false
  repo-token:
    description: 'Access token with read access to the repo containing action'
    required: true
  repo-name:
    description: 'The organization/user and repo where action is stored, with support for @ref'
    required: true
  build-script-name:
    description: 'Name of the script in package.json to be executed'
    required: true
    default: 'build'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'lock'
  color: 'green'
